# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	monotonic
PORTVERSION=	0.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Python 3 monotonic time module for python 2

LICENSE=	APACHE20

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

