# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	django-countries
PORTVERSION=	3.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	provides country choices for use with django

LICENSE=	BSD2CLAUSE

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

