# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	subprocess32
PORTVERSION=	3.2.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Python 3 subprocess module for python 2

LICENSE=	BSD2CLAUSE

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

