# Created by: Jeffrey Kubo <jmk@norse-corp.com>
# $FreeBSD$

PORTNAME=      django-netfields
PORTVERSION=   0.2.2
CATEGORIES=    www python
MASTER_SITES=  https://pypi.python.org/packages/source/d/django-netfields/ 
PKGNAMEPREFIX= ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=    jmk@norse-corp.com
COMMENT=       Django PostgreSQL netfields implementation

LICENSE=       BSD3CLAUSE

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>
